# Generated by Django 6.0.2 on 2026-03-09 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auteur',
            name='biographie',
            field=models.TextField(blank=True),
        ),
    ]
