# Generated by Django 6.0.2 on 2026-03-09 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_auteur_biographie'),
    ]

    operations = [
        migrations.AddField(
            model_name='livre',
            name='resume',
            field=models.TextField(blank=True),
        ),
    ]
