# Generated by Django 6.0.2 on 2026-03-09 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_livre_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livre',
            name='nombre_pages',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
