# Generated by Django 6.0.2 on 2026-03-16 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_alter_livre_nombre_pages'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprunt',
            name='retourne',
            field=models.BooleanField(default=False),
        ),
    ]
