# Generated by Django 6.0.2 on 2026-04-13 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0006_alter_auteur_id_alter_emprunt_id_alter_livre_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emprunt',
            name='retourne',
        ),
        migrations.AlterField(
            model_name='auteur',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='emprunt',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='livre',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
